### ISSUE TITLE
Add comments on projects / blogs posts 

### ISSUE THREAD

**Issue by edonadei** [TomKlotzPro/openNetwork#50]
Users need to comment, ask questions to creator of content

### Description
Project and blog pages should have a part with comments, where the users can read and write comments on the project.
We need to have a tree view of comments added to the content with intel on user that posted it, with possibility to upvote
![image](https://user-images.githubusercontent.com/21025565/105058565-a4a74b00-5a76-11eb-9302-40311364b9c9.png)

**Comment by TomKlotzPro** [comment]
Congrats @Ekeu !! Really nice feature
